# Generated by Django 2.2.10 on 2021-12-14 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('text', 'multiplechoose')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
