# Generated by Django 2.2.10 on 2021-12-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='second_selected',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='third_selected',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
